# Site settings
title: Optinalysis
email: nikhil@nikhilgopal.com
description: > # this means to ignore newlines until "baseurl:"
  infrequent logging of random things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nikhilgopal.com" # the base hostname & protocol for your site
twitter_username: nikhilgopal
github_username:  ngopal
permalink: /title.html

# Build settings
markdown: kramdown
